routes/abrigos.py
from flask import Blueprint, render_template, request, redirect, url_for
from models.models_clean import Abrigo

abrigos_route = Blueprint('abrigos', __name__, url_prefix='/abrigos')


@abrigos_route.route('/')
def lista_abrigos():
    abrigos = Abrigo.select()
    return render_template('lista_abrigos.html', abrigos=abrigos)


@abrigos_route.route('/new', methods=['GET'])
def form_abrigo():
    return render_template('form_abrigo.html')


@abrigos_route.route('/<int:abrigo_id>')
def detalhe_abrigo(abrigo_id):
    abrigo = Abrigo.get_or_none(Abrigo.id_abrigo == abrigo_id)
    return render_template('detalhe_abrigos.html', abrigo=abrigo)

@abrigos_route.route('/<int:abrigo_id>/edit', methods=['GET'])
def form_edit_abrigo(abrigo_id):
    abrigo = Abrigo.get_or_none(Abrigo.id_abrigo == abrigo_id)

    return render_template('form_abrigo.html', abrigo=abrigo)

@abrigos_route.route('/', methods=['POST'])
def inserir_abrigo():
    data = request.json

    # 1️⃣ Busca todos os códigos existentes
    codigos_existentes = [a.codigo_publico for a in Abrigo.select() if a.codigo_publico is not None]
    codigos_existentes.sort()

    # 2️⃣ Encontra o menor código livre
    proximo_codigo = 1
    for codigo in codigos_existentes:
        if codigo == proximo_codigo:
            proximo_codigo += 1
        else:
            break  # encontrou um "buraco", reutiliza


    novo_abrigo = Abrigo.create(
        nome=data['nome'],
        endereco=data['endereco'],
        capacidade_total=data['capacidade_total'],
        status_operacao=data['status_operacao'],
        tipo=data['tipo'],
        codigo_publico=proximo_codigo
    )

    return render_template('item_abrigo.html', abrigo=novo_abrigo)
    


@abrigos_route.route('/<int:abrigo_id>/editar', methods=['PUT'])
def editar_abrigo(abrigo_id):
    data = request.json
    abrigo = Abrigo.get_by_id(abrigo_id)
    abrigo.nome = data['nome']
    abrigo.endereco = data['endereco']
    abrigo.capacidade_total = data['capacidade_total']
    abrigo.status_operacao = data['status_operacao']
    abrigo.tipo = data['tipo']
    abrigo.save()

    return render_template('item_abrigo.html', abrigo=abrigo)

    


@abrigos_route.route('/<int:abrigo_id>/deletar', methods=['DELETE'])
def deletar_abrigo(abrigo_id):
    abrigo = Abrigo.get_by_id(abrigo_id)
    abrigo.delete_instance()
    

routes/assistidos.py
from flask import Blueprint, render_template, request
from models.models_clean import Assistido
assistidos_route = Blueprint('assistidos', __name__)


@assistidos_route.route('/')
def lista_assistidos():
  assistidos=Assistido.select()
  return render_template('lista_assistidos.html', assistidos=assistidos)

@assistidos_route.route('/', methods=['POST'])
def inserir_assistido():
    data = request.form or request.json
    # 1️⃣ Busca todos os códigos existentes
    codigos_existentes = [a.codigo_publico for a in Assistido.select() if a.codigo_publico is not None]
    codigos_existentes.sort()

    # 2️⃣ Encontra o menor código livre
    proximo_codigo = 1
    for codigo in codigos_existentes:
        if codigo == proximo_codigo:
            proximo_codigo += 1
        else:
            break  # encontrou um "buraco", reutiliza

    novo_usuario = Assistido.create(
        nome = data['nome'],
        data_nascimento = data['data_nascimento'],
        telefone = data['telefone'],
        genero = data['genero'],
        codigo_publico=proximo_codigo
    )
    

    return render_template('item_cliente.html', assistido=novo_usuario)

@assistidos_route.route('/new', methods=['GET'])
def form_assistido():
    return render_template('form_assistidos.html')

@assistidos_route.route('/<int:assistido_id>', methods=['GET'])
def detalhe_assistido(assistido_id):
    assistido = Assistido.get(Assistido.id_assistido == assistido_id)
    return render_template('detalhe_assistidos.html', assistido=assistido)

@assistidos_route.route('/<int:assistido_id>/edit', methods=['GET'])
def form_edit_assistido(assistido_id):
    assistido = Assistido.get(Assistido.id_assistido == assistido_id)

    return render_template('form_assistidos.html', assistido=assistido)

@assistidos_route.route('/<int:assistido_id>/update', methods=['PUT'])
def atualizar_assistido(assistido_id):
    data = request.form or request.json
    
    assistido = Assistido.get(Assistido.id_assistido == assistido_id)
    assistido.nome = data.get('nome')
    assistido.data_nascimento = data.get('data_nascimento') or None
    assistido.telefone = data.get('telefone')
    assistido.genero = data.get('genero')
    assistido.save()

    return render_template('item_cliente.html', assistido=assistido)

    
@assistidos_route.route('/<int:assistido_id>/delete', methods=['DELETE'])
def deletar_assistido(assistido_id):
  assistido = Assistido.get(Assistido.id_assistido == assistido_id)
  assistido.delete_instance()

  return {'deleted' : 'ok'}     


        

routes/home.py
from flask import Blueprint, render_template
from models.models_clean import Assistido
from peewee import *

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    assistido = Assistido.select().first()  # pega o primeiro
    return render_template('index.html', assistido=assistido)

routes/triagem.py
from logica_fuzzy import calculo_fuzzy
from flask import Blueprint, render_template, request, redirect, url_for
from models.models_clean import Assistido

triagem_route = Blueprint('triagem', __name__ , url_prefix='/triagem')

@triagem_route.route('/<int:assistido_id>', methods=['GET'])
def form_triagem(assistido_id):
    assistido = Assistido.get_or_none(Assistido.id_assistido == assistido_id)
    return render_template('form_triagem.html', assistido=assistido)

@triagem_route.route('/<int:assistido_id>', methods=['POST'])
def aplicar_triagem(assistido_id):
    assistido = Assistido.get_or_none(Assistido.id_assistido == assistido_id)

    # pega dados do json
    num_pessoas = int(request.form['num_pessoas'])
    num_vagas = int(request.form['num_vagas'])
    prioridade = float(request.form['prioridade'])

    resultado = calculo_fuzzy(num_pessoas, num_vagas, prioridade)

    # salva no banco

    assistido.prioridade_fuzzy = resultado['prioridade_fuzzy']
    assistido.status_prioridade = resultado['status']
    assistido.save()

    return redirect(url_for('assistidos.detalhe_assistido', assistido_id=assistido.id_assistido))
    

templates/detalhe_abrigos.html
<ul>
    <li>ID: {{ abrigo.codigo_publico }}</li>
    <li>NOME DO ABRIGO: {{ abrigo.nome }}</li>
    <li>ENDEREÇO: {{ abrigo.endereco }}</li>
    <li>CAPACIDADE TOTAL: {{abrigo.capacidade_total}}</li>
    <li>STATUS DE OPERAÇÃO: {{abrigo.status_operacao}}</li>
    <li>TIPO: {{abrigo.tipo}}</li>
</ul>

templates/detalhe_assistidos.html
<h2>Detalhes do Assistido</h2>

<p><strong>Nome:</strong> {{ assistido.nome }}</p>
<p><strong>Data de Nascimento:</strong> {{ assistido.data_nascimento }}</p>
<p><strong>Telefone:</strong> {{ assistido.telefone }}</p>
<p><strong>Gênero:</strong> {{ assistido.genero }}</p>

<hr>

<h3>Resultado da Triagem</h3>
{% if assistido.prioridade_fuzzy %}
  <p><strong>Prioridade Fuzzy:</strong> {{ assistido.prioridade_fuzzy | round(2) }}</p>
  <p><strong>Status:</strong> 
    {% if assistido.status_prioridade == "Aprovado" %}
      <span class="badge bg-success">{{ assistido.status_prioridade }}</span>
    {% elif assistido.status_prioridade == "Recusado" %}
      <span class="badge bg-danger">{{ assistido.status_prioridade }}</span>
    {% else %}
      <span class="badge bg-warning text-dark">{{ assistido.status_prioridade }}</span>
    {% endif %}
  </p>
{% else %}
  <p>Nenhuma triagem realizada ainda.</p>
{% endif %}

<hr>

<a href="{{ url_for('triagem.form_triagem', assistido_id=assistido.id_assistido) }}" class="btn btn-primary">
  Realizar Triagem
</a>
<a href="{{ url_for('home.home') }}" class="btn btn-secondary">Voltar</a>

templates/detalhe_operador.html
<ul>
    <li>ID: {{ operador.codigo_publico }}</li>
    <li>NOME: {{operador.nome}}</li>
    <li>FUNÇÃO: {{operador.funcao}}</li>

</ul>

templates/form_abrigo.html
<form class="c-form" 
    {% if abrigo %}
        action="{{ url_for('abrigos.editar_abrigo', abrigo_id=abrigo.id_abrigo) }}" 
    {% else %}
        action="{{ url_for('abrigos.inserir_abrigo') }}" 
    {% endif %}  
        
        method="{% if abrigo %}PUT{% else %}POST{% endif %}"
         
            
            {% if abrigo %}
                c-swap=".abrigo-{{abrigo.id_abrigo}}"      
            {% else %}
                c-append="#lista-abrigos"
            {% endif %}
            c-reload-container="true"
        >

  <div class="mb-3">
    <label class="form-label">Nome:</label>
    <input type="text" class="form-control" name="nome" {% if abrigo %}value="{{abrigo.nome}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Endereço:</label>
    <input type="text" class="form-control" name="endereco" {% if abrigo %}value="{{abrigo.endereco}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Capacidade Total:</label>
    <input type="number" class="form-control" name="capacidade_total" {% if abrigo %}value="{{abrigo.capacidade_total}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Status de Operação:</label>
    <input type="text" class="form-control" name="status_operacao" {% if abrigo %}value="{{abrigo.status_operacao}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Tipo:</label>
    <input type="text" class="form-control" name="tipo" {% if abrigo %}value="{{abrigo.tipo}}"{% endif %}>
  </div>

  {% if abrigo %}
  <button type="submit" class="btn btn-primary">
    Salvar
  </button>
  {% else %}
  <button type="submit" class="btn btn-primary" c-post="{{ url_for('abrigos.inserir_abrigo') }}">
    Criar Abrigo
  </button>
  {% endif %}
</form>

templates/form_assistidos.html
<form class="c-form" 
       
    {% if assistido %}
        action="{{ url_for('assistidos.atualizar_assistido', assistido_id=assistido.id_assistido) }}" 
    {% else %}
        action="{{ url_for('assistidos.inserir_assistido') }}" 
    {% endif %}  
        
        method="{% if assistido %}PUT{% else %}POST{% endif %}"
        


        {% if assistido %}
            c-swap=".assistido-{{assistido.id_assistido}}"      
        {% else %}
            c-append="#lista-assistidos"
        {% endif %}
        c-reload-container="true"
        >

        
      

  <div class="mb-3">
    <label class="form-label">Nome Completo:</label>
    <input type="text" class="form-control" name="nome" {% if assistido %}value="{{assistido.nome}}"{% endif %}>
  </div>

  <div class="mb-3">
  <label for="data_nascimento">Data de Nascimento:</label>
  <input type="date" id="data_nascimento" name="data_nascimento" 
       {% if assistido and assistido.data_nascimento %}value="{{ assistido.data_nascimento.isoformat() if assistido.data_nascimento else '' }}"{% endif %}>

  </div>

  <div class="mb-3">
  <label for="telefone">Telefone:</label>
  <input type="tel" id="telefone" name="telefone" placeholder="(99) 99999-9999" {% if assistido %}value="{{assistido.telefone}}"{% endif %}>
  </div>

  <div class="mb-3">
    <label class="form-label">Gênero:</label>
    <input type="text" class="form-control" name="genero" {% if assistido %}value="{{assistido.genero}}"{% endif %}>
  </div>

  {% if assistido %}
  <button type="submit" class="btn btn-primary">
    Salvar
 </button>
  {% else %}
 <button type="submit" class="btn btn-primary" c-post="{{ url_for('assistidos.inserir_assistido') }}">
    Criar Assistido
 </button>
  {% endif %}
</form>

templates/form_operador.html
<form class="c-form" 
       
    {% if operador %}
        action="{{ url_for('operadores.editar_operador', operador_id=operador.id_operador) }}" 
    {% else %}
        action="{{ url_for('operadores.inserir_operador') }}" 
    {% endif %}  
        
        method="{% if operador %}PUT{% else %}POST{% endif %}"
        


        {% if operador %}
            c-swap=".operador-{{operador.id_operador}}"      
        {% else %}
            c-append="#lista-operadores"
        {% endif %}
        c-reload-container="true"
        >

        
      

  <div class="mb-3">
    <label class="form-label">Nome Completo:</label>
    <input type="text" class="form-control" name="nome" {% if operador %}value="{{operador.nome}}"{% endif %}>
  </div>

  <div class="mb-3">
  <label for="data_nascimento">Função:</label>
  <input type="text" class="form-control" id="funcao" name="funcao" {% if operador %}value="{{operador.funcao}}"{% endif %}>
  </div>


  {% if operador %}
  <button type="submit" class="btn btn-primary">
    Salvar
 </button>
  {% else %}
 <button type="submit" class="btn btn-primary" c-post="{{ url_for('operadores.inserir_operador') }}">
    Criar Operador
 </button>
  {% endif %}
</form>

templates/form_triagem.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Triagem</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        <h1>Formulário de Triagem</h1>

        <form method="POST" action="{{ url_for('triagem.aplicar_triagem', assistido_id=assistido.id_assistido) }}">
            <label for="num_pessoas">Quantidade de Pessoas:</label>
            <input type="number" id="num_pessoas" name="num_pessoas" required min="0">

            <label for="num_vagas">Quantidade de Vagas:</label>
            <input type="number" id="num_vagas" name="num_vagas" required min="0">

            <label for="prioridade">Prioridade (0 a 1):</label>
            <input type="number" id="prioridade" name="prioridade" step="0.01" min="0" max="1" required>

            <button type="submit" class="btn">Calcular Triagem</button>
        </form>

        <!-- Botão de voltar para Home -->
        <a href="{{ url_for('home.home') }}" class="btn-voltar">⬅ Voltar para Home</a>
    </div>
</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">

    <title>Teste Sistema de Alocação de Desabrigados</title>
  </head>
  <body>

    <div class="container">

      <h1>Sistema de Alocação de Desabrigados</h1>
      <hr>
      <h2>Cadastro de Abrigos</h2>  
    
      <div id="form-abrigo" c-container="{{ url_for('abrigos.form_abrigo') }}"></div>
    
      <hr>  
      <h2>Cadastro de Assistidos</h2> 
      <!--Formulário de Assistidos-->
      <div id="form-assistido" c-container="{{ url_for('assistidos.form_assistido') }}"></div>
      
      <hr>  
      <h2>Cadastro de Operadores</h2> 
      <!--Formulário de Operadores-->
      <div id="form-operador" c-container="{{ url_for('operadores.form_operador') }}"></div>

      <hr>
      <!--Lista de Assistidos-->

      <h2>Lista de Abrigos</h2>

      <div c-container="{{url_for('abrigos.lista_abrigos')}}"></div>



        
      <hr>
      <!--Lista de Assistidos-->

      <h2>Lista de Assistidos</h2>

      <div c-container="{{url_for('assistidos.lista_assistidos')}}"></div>
 
      
      <hr>
      <!--Lista de Assistidos-->

      <h2>Lista de Operadores</h2>

      <div c-container="{{url_for('operadores.lista_operadores')}}"></div>
 
       

    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="exibir-assistido"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js' ) }}"></script>
   
  </body>
</html>


<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="exibir-abrigo"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js' ) }}"></script>
   
  </body>
</html>


<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="exibir-operador"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js' ) }}"></script>
   
  </body>
</html>

templates/item_abrigo.html
<tr class="abrigo-{{abrigo.id_abrigo}}">
      <th scope="row">{{ abrigo.codigo_publico }}</th>
      <td>{{ abrigo.nome }}</td>
      <td>{{ abrigo.endereco }}</td>
      <td>{{ abrigo.capacidade_total }}</td>
      <td>{{ abrigo.status_operacao }}</td>
      <td>{{ abrigo.tipo }}</td>
      <td>
        
        
        <button class="btn btn-secondary" 
        c-get="{{ url_for('abrigos.detalhe_abrigo', abrigo_id=abrigo.id_abrigo) }}"
        c-target="#exibir-abrigo"
        data-bs-toggle="modal" data-bs-target="#exampleModal2"
        >
        Ver
    </button>
        <button class="btn btn-primary" 
        c-get="{{ url_for('abrigos.form_edit_abrigo', abrigo_id=abrigo.id_abrigo) }}"
        c-target="#form-abrigo"
        >
        Editar
    </button>
        <button class="btn btn-danger" 
        c-delete="{{ url_for('abrigos.deletar_abrigo', abrigo_id=abrigo.id_abrigo) }}" 
        c-remove-closest="tr">
        Deletar
    </button>
      </td>
 </tr>

templates/item_cliente.html
<tr class="assistido-{{assistido.id_assistido}}">
      <th scope="row">{{ assistido.codigo_publico }}</th>
      <td>{{ assistido.nome }}</td>
      <td>{{ assistido.data_nascimento }}</td>
      <td>{{ assistido.telefone }}</td>
      <td>{{ assistido.genero }}</td>
      <td>
        
        
        <button class="btn btn-secondary" 
        c-get="{{ url_for('assistidos.detalhe_assistido', assistido_id=assistido.id_assistido) }}"
        c-target="#exibir-assistido"
        data-bs-toggle="modal" data-bs-target="#exampleModal"
        >
        Ver
    </button>
        <button class="btn btn-primary" 
        c-get="{{ url_for('assistidos.form_edit_assistido', assistido_id=assistido.id_assistido) }}"
        c-target="#form-assistido"
        >
        Editar
    </button>
        <button class="btn btn-danger" 
        c-delete="{{ url_for('assistidos.deletar_assistido', assistido_id=assistido.id_assistido) }}" 
        c-remove-closest="tr">
        Deletar
    </button>
      </td>
 </tr>

templates/item_operador.html
<tr class="operador-{{operador.id_operador}}">
      <th scope="row">{{ operador.codigo_publico }}</th>
      <td>{{ operador.nome }}</td>
      <td>{{ operador.funcao }}</td>
      <td>
        
        
        <button class="btn btn-secondary" 
        c-get="{{ url_for('operadores.detalhe_operador', operador_id=operador.id_operador) }}"
        c-target="#exibir-operador"
        data-bs-toggle="modal" data-bs-target="#exampleModal3"
        >
        Ver
    </button>
        <button class="btn btn-primary" 
        c-get="{{ url_for('operadores.form_edit_operador', operador_id=operador.id_operador) }}"
        c-target="#form-operador"
        >
        Editar
    </button>
        <button class="btn btn-danger" 
        c-delete="{{ url_for('operadores.deletar_operador', operador_id=operador.id_operador) }}" 
        c-remove-closest="tr">
        Deletar
    </button>
      </td>
 </tr>

templates/lista_abrigos.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Endereço</th>
      <th scope="col">Capacidade Total</th>
      <th scope="col">Status da Operação</th>
      <th scope="col">Tipo</th>
    </tr>
  </thead>
  <tbody id="lista-abrigos">
    
    {% for abrigo in abrigos %}
          {% include 'item_abrigo.html' %}
    {% endfor %}
    
  </tbody>
</table>

templates/lista_assistidos.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Data de Nascimento</th>
      <th scope="col">Telefone</th>
      <th scope="col">Gênero</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody id="lista-assistidos">
    
    {% for assistido in assistidos %}
          {% include 'item_cliente.html' %}
    {% endfor %}
    
  </tbody>
</table>

templates/lista_operador.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Função</th>
    </tr>
  </thead>
  <tbody id="lista-operadores">
    
    {% for operador in operadores %}
          {% include 'item_operador.html' %}
    {% endfor %}
    
  </tbody>
</table>